from __future__ import annotations

import re
import pandas as pd
import os


def _word_count(text: str) -> int:
    if not text or not isinstance(text, str):
        return 0
    return len(text.split())


def _looks_autogenerated(name: str) -> bool:
    if not name or not isinstance(name, str):
        return True
    # Contains digits, or is generic pattern like "Amazon Customer", "A. Customer"
    if re.search(r"\d", name):
        return True
    generic = re.compile(r"^(amazon customer|a\.\s*customer|customer|user|buyer)$", re.I)
    if generic.match(name.strip()):
        return True
    return False


def _extract_date_string(date_val) -> str:
    """Pull a usable date string out of whatever the API returns."""
    if not date_val:
        return ""
    # Rainforest returns {"raw": "...", "utc": "2024-01-15T00:00:00.000Z"}
    if isinstance(date_val, dict):
        return date_val.get("utc") or date_val.get("raw") or ""
    return str(date_val)


def _parse_date(date_val) -> str:
    """Normalize date to YYYY-MM-DD string for grouping; return empty string on failure."""
    raw = _extract_date_string(date_val)
    if not raw:
        return ""
    # ISO UTC string: "2024-01-15T00:00:00.000Z"
    try:
        return pd.to_datetime(raw).strftime("%Y-%m-%d")
    except Exception:
        pass
    # Fallback: "Reviewed in the United States on January 15, 2024"
    match = re.search(r"(\w+ \d{1,2}, \d{4})", raw)
    if match:
        try:
            return pd.to_datetime(match.group(1)).strftime("%Y-%m-%d")
        except Exception:
            pass
    return ""


def filter_fake_reviews(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, dict]:
    """
    Score each review 0-100 for trustworthiness.
    Returns (trusted_reviews, flagged_reviews, stats).
    """
    if df.empty:
        empty = df.copy()
        stats = {
            "total_reviews_analyzed": 0,
            "trusted_count": 0,
            "flagged_count": 0,
            "fake_percentage": 0.0,
            "verified_purchase_rate": 0.0,
            "average_trust_score": 0.0,
        }
        return empty, empty, stats

    scored = df.copy()

    # Normalize columns so scoring never KeyErrors
    for col in ["rating", "body", "verified_purchase", "reviewer_name", "helpful_votes", "date"]:
        if col not in scored.columns:
            scored[col] = None

    # Pre-compute date groups for same-day burst detection
    scored["_date_key"] = scored["date"].apply(_parse_date)
    date_counts = scored["_date_key"].value_counts()

    scores = []
    for _, row in scored.iterrows():
        score = 50  # neutral baseline

        verified = row["verified_purchase"]
        body = row["body"] if isinstance(row["body"], str) else ""
        words = _word_count(body)
        rating = row["rating"]
        name = row["reviewer_name"]
        helpful = row.get("helpful_votes", None)
        date_key = row["_date_key"]

        # --- TRUST SIGNALS ---
        if verified is True:
            score += 40
        if words > 100:
            score += 20
        if words > 200:
            score += 10
        if rating == 3:
            score += 10
        # reviewer_count > 1 means they've reviewed other products
        reviewer_count = row.get("reviewer_review_count", None)
        if isinstance(reviewer_count, (int, float)) and reviewer_count > 1:
            score += 10
        if isinstance(helpful, (int, float)) and helpful > 0:
            score += 10

        # --- SUSPICION SIGNALS ---
        if verified is False:
            score -= 30
        if words < 20:
            score -= 40
        if date_key and date_counts.get(date_key, 0) >= 3:
            score -= 20
        if rating == 5 and words < 10:
            score -= 30
        if rating == 1 and words < 10:
            score -= 20
        if _looks_autogenerated(name):
            score -= 15

        scores.append(max(0, min(100, score)))

    scored["trust_score"] = scores
    scored = scored.drop(columns=["_date_key"])

    trusted = scored[scored["trust_score"] >= 50].reset_index(drop=True)
    flagged = scored[scored["trust_score"] < 50].reset_index(drop=True)

    total = len(scored)
    verified_count = scored["verified_purchase"].eq(True).sum()

    stats = {
        "total_reviews_analyzed": total,
        "trusted_count": len(trusted),
        "flagged_count": len(flagged),
        "fake_percentage": round(len(flagged) / total * 100, 1) if total else 0.0,
        "verified_purchase_rate": round(verified_count / total * 100, 1) if total else 0.0,
        "average_trust_score": round(scored["trust_score"].mean(), 1) if total else 0.0,
    }

    return trusted, flagged, stats


def _parse_date_to_datetime(date_val) -> pd.Timestamp | None:
    raw = _extract_date_string(date_val)
    if not raw:
        return None
    try:
        return pd.to_datetime(raw, utc=True).tz_convert(None)
    except Exception:
        pass
    match = re.search(r"(\w+ \d{1,2}, \d{4})", raw)
    if match:
        try:
            return pd.to_datetime(match.group(1))
        except Exception:
            pass
    return None


def compute_sentiment_trends(reviews_df: pd.DataFrame) -> dict:
    empty_result = {
        "monthly_data": [],
        "trend_direction": "stable",
        "trend_magnitude": 0.0,
        "spike_months": [],
        "insight": "Not enough data to compute trends.",
    }

    if reviews_df.empty or "date" not in reviews_df.columns:
        return empty_result

    df = reviews_df.copy()
    df["_dt"] = df["date"].apply(_parse_date_to_datetime)
    df = df.dropna(subset=["_dt"])

    if df.empty:
        return empty_result

    df["_month"] = df["_dt"].dt.to_period("M")

    verified_col = "verified_purchase" if "verified_purchase" in df.columns else None

    monthly_data = []
    for period, group in sorted(df.groupby("_month"), key=lambda x: x[0]):
        ratings = pd.to_numeric(group["rating"], errors="coerce").dropna()
        count = len(group)
        avg_rating = round(ratings.mean(), 2) if not ratings.empty else None
        complaint_rate = round((ratings <= 2).sum() / len(ratings) * 100, 1) if not ratings.empty else 0.0
        praise_rate = round((ratings >= 4).sum() / len(ratings) * 100, 1) if not ratings.empty else 0.0

        if verified_col:
            vp_rate = round(group[verified_col].eq(True).sum() / count * 100, 1)
        else:
            vp_rate = None

        monthly_data.append({
            "month": str(period),
            "review_count": count,
            "average_rating": avg_rating,
            "verified_purchase_rate": vp_rate,
            "complaint_rate": complaint_rate,
            "praise_rate": praise_rate,
        })

    if len(monthly_data) < 2:
        return {
            "monthly_data": monthly_data,
            "trend_direction": "stable",
            "trend_magnitude": 0.0,
            "spike_months": [],
            "insight": "Only one month of data — trend analysis requires multiple months.",
        }

    # Trend: compare last 3 months vs prior 3 months by average rating
    ratings_series = [m["average_rating"] for m in monthly_data if m["average_rating"] is not None]
    if len(ratings_series) >= 6:
        recent_avg = sum(ratings_series[-3:]) / 3
        prior_avg = sum(ratings_series[-6:-3]) / 3
    elif len(ratings_series) >= 2:
        mid = len(ratings_series) // 2
        recent_avg = sum(ratings_series[mid:]) / len(ratings_series[mid:])
        prior_avg = sum(ratings_series[:mid]) / len(ratings_series[:mid])
    else:
        recent_avg = prior_avg = ratings_series[0]

    if prior_avg == 0:
        trend_magnitude = 0.0
    else:
        trend_magnitude = round((recent_avg - prior_avg) / prior_avg * 100, 1)

    if trend_magnitude > 2:
        trend_direction = "improving"
    elif trend_magnitude < -2:
        trend_direction = "declining"
    else:
        trend_direction = "stable"

    # Spike detection: flag months where complaint rate > overall avg + 20pp
    all_complaint_rates = [m["complaint_rate"] for m in monthly_data]
    avg_complaint_rate = sum(all_complaint_rates) / len(all_complaint_rates)
    spike_months = [
        m["month"] for m in monthly_data
        if m["complaint_rate"] > avg_complaint_rate + 20
    ]

    # Insight sentence
    if trend_direction == "improving":
        insight = f"Sentiment is improving — recent average rating is {trend_magnitude:+.1f}% higher than the prior period."
    elif trend_direction == "declining":
        insight = f"Sentiment is declining — recent average rating is {trend_magnitude:.1f}% lower than the prior period."
    else:
        insight = f"Sentiment is stable across the review period with no significant rating shift."

    if spike_months:
        insight += f" Complaint spike detected in: {', '.join(spike_months)}."

    return {
        "monthly_data": monthly_data,
        "trend_direction": trend_direction,
        "trend_magnitude": trend_magnitude,
        "spike_months": spike_months,
        "insight": insight,
    }


def compute_rating_distribution(reviews_df: pd.DataFrame) -> dict:
    if reviews_df.empty or "rating" not in reviews_df.columns:
        return {str(i): {"count": 0, "percentage": 0.0} for i in range(1, 6)}

    ratings = pd.to_numeric(reviews_df["rating"], errors="coerce").dropna()
    total = len(ratings)
    distribution = {}
    for star in range(1, 6):
        count = int((ratings == star).sum())
        distribution[str(star)] = {
            "count": count,
            "percentage": round(count / total * 100, 1) if total else 0.0,
        }
    return distribution


if __name__ == "__main__":
    import json
    from rainforest import fetch_product_reviews

    result = fetch_product_reviews("B07PXGQC1Q")
    print(f"Product: {result['product_info']['title']}\n")

    df = result["reviews"]
    trusted, flagged, stats = filter_fake_reviews(df)

    print("=== Filter Stats ===")
    for k, v in stats.items():
        print(f"  {k}: {v}")

    print("\n=== Rating Distribution ===")
    dist = compute_rating_distribution(df)
    for star, data in dist.items():
        bar = "█" * int(data["percentage"] / 5)
        print(f"  {star}★  {bar} {data['count']} ({data['percentage']}%)")

    print("\n=== Sentiment Trends ===")
    trends = compute_sentiment_trends(df)
    print(f"  Trend direction : {trends['trend_direction']}")
    print(f"  Trend magnitude : {trends['trend_magnitude']:+.1f}%")
    print(f"  Spike months    : {trends['spike_months'] or 'none'}")
    print(f"  Insight         : {trends['insight']}")
    print("\n  Monthly breakdown:")
    for m in trends["monthly_data"]:
        print(f"    {m['month']}  reviews={m['review_count']}  avg_rating={m['average_rating']}  "
              f"complaint={m['complaint_rate']}%  praise={m['praise_rate']}%")
